# Generated by Django 4.0.4 on 2022-09-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["id"]},
        ),
    ]
